### ISSUE TITLE
Mailchimp list

### ISSUE THREAD

**Issue by kbariotis** [skgtech/devit2016#3]
We need to create a new List for the 2016.

**Comment by thanpolas** [comment]
Why?
Use the original one

---
Thanasis Polychronakis

http://thanpol.as





On Sat, Oct 24, 2015 at 4:16 AM -0700, "Kostas Bariotis" <notifications@github.com> wrote:












We need to create a new List for the 2016.

**Comment by kbariotis** [comment]
Ok no prob. I thought it would be spam.

**Comment by thanpolas** [comment]
Nope, everyone opted in

---
Thanasis Polychronakis

http://thanpol.as





On Sat, Oct 24, 2015 at 9:51 AM -0700, "Kostas Bariotis" <notifications@github.com> wrote:










Ok no prob. I thought it would be spam.

On Oct 24, 2015 6:12 PM, "Thanasis Polychronakis" <notifications@github.com>

wrote:



> Why?

> Use the original one

>

> ---

> Thanasis Polychronakis

>

> http://thanpol.as

>

>

>

>

>

> On Sat, Oct 24, 2015 at 4:16 AM -0700, "Kostas Bariotis" <
